<x-layouts::app :title="$title">
    <div class="mx-auto max-w-3xl space-y-6 p-6 lg:p-10"><a class="text-sm font-semibold text-amber-600" href="{{ url()->previous() }}">Volver</a><div><p class="text-sm font-semibold uppercase tracking-[0.18em] text-amber-600">{{ $team->name }}</p><h1 class="mt-2 text-3xl font-bold">{{ $title }}</h1></div>
        <form method="POST" action="{{ isset($item) ? route($resource.'.update', [$team->slug, $item]) : route($resource.'.store', $team->slug) }}" class="space-y-5 rounded-2xl border border-zinc-200 bg-white p-6 dark:border-zinc-700 dark:bg-zinc-900">@csrf @isset($item) @method('PUT') @endisset
            @if ($resource === 'comentarios')<label class="block text-sm font-semibold">ID de publicación<input name="id_publicacion" type="number" value="{{ old('id_publicacion', $item->id_publicacion ?? '') }}" required class="mt-2 block w-full rounded-lg border-zinc-300 dark:border-zinc-600 dark:bg-zinc-800"></label>@endif
            @if ($resource === 'noticias')<label class="block text-sm font-semibold">Título<input name="titulo" value="{{ old('titulo', $item->titulo ?? '') }}" required maxlength="180" class="mt-2 block w-full rounded-lg border-zinc-300 dark:border-zinc-600 dark:bg-zinc-800"></label><label class="block text-sm font-semibold">Categoría<input name="categoria" value="{{ old('categoria', $item->categoria ?? '') }}" class="mt-2 block w-full rounded-lg border-zinc-300 dark:border-zinc-600 dark:bg-zinc-800"></label>@endif
            @if ($resource === 'comunidad')<label class="block text-sm font-semibold">Nombre<input name="nombre" value="{{ old('nombre', $item->nombre ?? '') }}" required maxlength="100" class="mt-2 block w-full rounded-lg border-zinc-300 dark:border-zinc-600 dark:bg-zinc-800"></label>@endif
            @if ($resource === 'problemas')<label class="block text-sm font-semibold">Título<input name="titulo" value="{{ old('titulo', $item->titulo ?? '') }}" required maxlength="160" class="mt-2 block w-full rounded-lg border-zinc-300 dark:border-zinc-600 dark:bg-zinc-800"></label><div class="grid gap-4 sm:grid-cols-2"><label class="block text-sm font-semibold">Prioridad<select name="prioridad" class="mt-2 block w-full rounded-lg border-zinc-300 dark:border-zinc-600 dark:bg-zinc-800">@foreach (['baja','media','alta','critica'] as $priority)<option @selected(old('prioridad', $item->prioridad ?? 'media') === $priority)>{{ $priority }}</option>@endforeach</select></label>@isset($item)<label class="block text-sm font-semibold">Estado<select name="estado" class="mt-2 block w-full rounded-lg border-zinc-300 dark:border-zinc-600 dark:bg-zinc-800">@foreach (['abierto','en_progreso','resuelto','cerrado'] as $state)<option @selected(old('estado', $item->estado) === $state)>{{ $state }}</option>@endforeach</select></label>@endisset</div>@endif
            @if ($resource !== 'comentarios')<label class="block text-sm font-semibold">Descripción o contenido<textarea name="{{ $resource === 'noticias' ? 'contenido' : 'descripcion' }}" rows="8" required class="mt-2 block w-full rounded-lg border-zinc-300 dark:border-zinc-600 dark:bg-zinc-800">{{ old($resource === 'noticias' ? 'contenido' : 'descripcion', $item->contenido ?? $item->descripcion ?? '') }}</textarea></label>@else<label class="block text-sm font-semibold">Comentario<textarea name="contenido" rows="6" required class="mt-2 block w-full rounded-lg border-zinc-300 dark:border-zinc-600 dark:bg-zinc-800">{{ old('contenido', $item->contenido ?? '') }}</textarea></label>@endif
            @if ($errors->any())<div class="text-sm text-red-600">{{ $errors->first() }}</div>@endif
            <button class="rounded-lg bg-amber-500 px-5 py-2 font-semibold text-zinc-950 hover:bg-amber-400">Guardar</button>
        </form>
    </div>
</x-layouts::app>